name: Deploy

on:
  push:
    branches:
      - no-branch

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        run: |
          sudo kubectl apply -f manifests/
